title: DNHS Flocker 
description: "Social Media for Del Norte High School"
owner_name: John Mortensen
github_username: nighthawkcoders
github_repo: "flocker_frontend" 
baseurl: "/flocker_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/academics.md
  - navigation/clubs.md
  - navigation/events.md
  - navigation/hangouts.md
  - navigation/sports.md
  - navigation/authentication/login.md